numero1 = int(input("introduce el primer numero"))
numero2 = int(input("introduce el segundo numero"))
suma = (numero1 + numero2)
resta = (numero1 - numero2)
division = (numero1 / numero2)
multiplicacion = (numero1 * numero2)

print("suma " + str(suma))
print("resta " + str(resta))
print("division " + str(division))
print("multiplicacion " + str(multiplicacion))